### ISSUE TITLE
Disappearing particles after resuming melody

### ISSUE THREAD

**Issue by morshielt** [zofja/mubbo#7]
Po klikukrotnym zapauzowaniu i wznowieniu część particli znika. Najłatwiej zauważalne przy > 7 particlach. 
Prawdopodobnie nie wszystkie zdążą przejść z jednej do drugiej generacji i część przepada.

**Comment by zofja** [comment]
Wychwyciłam issue przy 2 particle'ach, zapisałam output do pliku:
[log_2019_05_02.txt](https://github.com/zofja/mubbo/files/3139378/log_2019_05_02.txt)

**Comment by zofja** [comment]
To pewnie kwestia tego, że stany particli to tylko kierunki. Error `Index 4 out of bounds for length 4` oznacza, że próbujemy wziąć Direction, który nie istnieje. Wynika to z tego, że nie jest obsługiwany w GUI stan kolizji. Możnaby zmienić nazwę klasy `Direction` na `State` i dodać do enuma stan `COLLISION`. Wtedy przy wielokrotnym i szybkim klikaniu przycisku `Play` byłoby wiadomo, że particle są nadal w kolizji. Notabene wychwyciłam jeszcze jeden case – freeze przy kolizji, log tutaj:
[log_2019_05_02_2.txt](https://github.com/zofja/mubbo/files/3139455/log_2019_05_02_2.txt)

**Comment by morshielt** [comment]
Tylko jak dodamy COLLISION, to odnijanie polegające na ([akt_stan + 2] % 4) przestanie działać jakby co~

**Comment by zofja** [comment]
> Tylko jak dodamy COLLISION, to odnijanie polegające na ([akt_stan + 2] % 4) przestanie działać jakby co~

Racja...

Zasadniczo case jest taki:
- GUI podaje poczatkowy stan planszy
- play
- kolizja, symbol ustawiany na COLLISION
- GUI otrzymuje symbol COLLISION i zmienia wygląd
- GUI odsyła stan planszy z symbolem COLLISION
- core nie obsluguje symbolu COLLISION (insert rzuca error array out of bounds)
- play
- cząsteczki znikły, ponieważ nie zostały *ponownie* poprawnie dodane na planszę

Naprawiłam to dodając ifa w klasie `GridManager` – trzeba czyścić listę i dodawać cząsteczki z powrotem wtw. nie jest kolizja, a wynika to z tego, że kolizja to jest taki "meta stan".
