### ISSUE TITLE
Transfer repo to organization account

### ISSUE THREAD

**Issue by zofja** [zofja/mubbo#8]
Robimy przeprowadzkę?

[Wygląda easy](https://help.github.com/en/articles/transferring-a-repository)

**Comment by morshielt** [comment]
Jak dla mnie możesz, jak nie mamy pomysłu na nazwę to może być po prostu 'mubbo', chyba, że ktoś ma jakieś obiekcje xD

**Comment by rotifyld** [comment]
a dlaczego?
bo ja widzę tylko minus w postaci konieczności utrzymywania nowego konta, na którym będzie znikoma (hopefully większa niż jeden) ilość projektów

**Comment by morshielt** [comment]
Skoro nadal tego nie zrobilśmy, to pewnie już nie zrobimy~
